# Generated by Django 3.2.5 on 2021-09-21 10:28

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bio', models.TextField()),
                ('contact', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starproject.profile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.IntegerField(choices=[(1, 'very low'), (2, '2'), (3, '3'), (4, '4'), (5, 'Avarage'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, 'Exellent')], default=0)),
                ('design', models.IntegerField(choices=[(1, 'very low'), (2, '2'), (3, '3'), (4, '4'), (5, 'Avarage'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, 'Exellent')], default=0)),
                ('usability', models.IntegerField(choices=[(1, 'very low'), (2, '2'), (3, '3'), (4, '4'), (5, 'Avarage'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, 'Exellent')], default=0)),
                ('average', models.DecimalField(decimal_places=2, default=1, max_digits=30)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starproject.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('bio', models.TextField()),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starproject.project')),
                ('projects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
